### PR TITLE
Refactor a bit

### PR DESCRIPTION
**Pull request by sarahsturgeon**

### CODE REVIEW

**Review by justinmuskopf — APPROVED** [review]
What is `usermessage`?

**Comment by sarahsturgeon** [comment]
You send messages to the users - telling them to run code

**Comment by sarahsturgeon** [comment]
also it's deprecated: https://wiki.garrysmod.com/page/usermessage/Hook

**Comment by sarahsturgeon** [comment]
we should use netmessages: https://wiki.garrysmod.com/page/Category:net

**Comment by sarahsturgeon** [comment]
I'm going to merge this, but it's untested.

**Pull request merged**
